
try {
  methodThatMightCauseAnError();
} 
catch (ex){
  alert(ex.message); 
}
finally{

}